export const CREATE_GALLARY = "CREATE_GALLARY";
export const EDIT_GALLARY = "EDIT_GALLARY";
export const DELETE_GALLARY = "DELETE_GALLARY";
export const GET_ALL_GALLARY = "GET_ALL_GALLARY";
export const UPLOAD_GALLARY_IMAGE = "UPLOAD_GALLARY_IMAGE";
