export const CREATE_SINGLE_CATEGORY = "CREATE_SINGLE_CATEGORY";
export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
