export const CREATE_HOME_BANNER = "CREATE_HOME_BANNER";
export const GET_ALL_HOME_BANNER = "GET_ALL_HOME_BANNER";
export const UPLOAD_HOME_BANNER_IMAGE = "UPLOAD_HOME_BANNER_IMAGE";
export const DELETE_HOME_BANNER = "DELETE_HOME_BANNER";
export const EDIT_HOME_BANNER = "EDIT_HOME_BANNER";

export const CREATE_POP_UP="CREATE_POP_UP"
export const DELETE_POP_UP="DELETE_POP_UP"
export const GET_POP_UP="GET_POP_UP"


